[docs] 프로필 추가
SSAFY-10th/algorithm pull request #13
Opened 2023-07-15 11:41 UTC by Yg-Hong

## 📣 Related Issue
SSAFY 10기 서울 11반 홍윤기입니다.
프로필 추가를 위해 README.md 수정하고 PR 올립니다.

## 🌁 Background
프로필 추가

## 👩‍💻 Contents
README.md 팀 테이블에 이름과 사진 추가하였습니다.

## 📱 Screenshot

## 📝 Review Note

## 📬 Reference

2023-07-15 11:48 UTC, minjae9610 requested changes
환영합니다.
수정사항 반영해주시면 바로 Approve 드릴께요 👍

2023-07-15 11:48 UTC, minjae9610 commented on README.md
> +|![chjcode](https://avatars.githubusercontent.com/u/107929019)|![SeokJuGo](https://avatars.githubusercontent.com/u/116260619)|![WhalesBob](https://avatars.githubusercontent.com/u/96509257)|[![Cha Cha
```suggestion
|![chjcode](https://avatars.githubusercontent.com/u/107929019)|![SeokJuGo](https://avatars.githubusercontent.com/u/116260619)|![WhalesBob](https://avatars.githubusercontent.com/u/96509257)|[![Cha Cha](https://avatars.githubusercontent.com/u/90785316)](https://github.com/ChaCha3088)|[![Yg-Hong](https://avatars.githubusercontent.com/u/89956603)](https://github.com/Yg-Hong)
```
뒤의 `?v=4`는 이미지의 크기 태그라 동적 스케일링을 지원하는 마크다운 문서에서는 필요하지 않을것 같아요 :)

2023-07-15 12:12 UTC, minjae9610 approved these changes
LGTM

2023-07-21 06:28 UTC, ChaCha3088 approved these changes

2023-07-22 14:09 UTC, merged