Update README.md
SSAFY-10th/algorithm pull request #30
Opened 2023-07-25 08:44 UTC by bellday

## 🌁 Background

프로필 추가를 위해 작성

2023-07-25 08:57 UTC, minjae9610 requested changes
환영합니다 :)

2023-07-25 08:57 UTC, minjae9610 commented on README.md
> +|[Cha Cha](https://github.com/ChaCha3088)|[3o14](https://github.com/3o14)|[Yg-Hong](https://github.com/Yg-Hong)|[KIM SEI](https://github.com/KIMSEI1124)|       [BELLDAY](https://github.com/bellday)|
```suggestion
|[Cha Cha](https://github.com/ChaCha3088)|[3o14](https://github.com/3o14)|[Yg-Hong](https://github.com/Yg-Hong)|[KIM SEI](https://github.com/KIMSEI1124)|[BELLDAY](https://github.com/bellday)|
```
여기만 간격이 남아있네요?

2023-07-25 09:29 UTC, minjae9610 approved these changes
LGTM

2023-07-31 06:40 UTC, cJinu approved these changes
화이팅 입니다.!

2023-07-31 07:14 UTC, merged