[docs] add kgh2120 profile
SSAFY-10th/algorithm pull request #39
Opened 2023-07-31 06:32 UTC by kgh2120

## 🌁 Background
리드미 프로필 정보 추가

## 👩‍💻 Contents
안녕하세요! 리드미에 제 프로필을 추가했습니다.

## 👀ETC
서울 9반 김규현입니다.
저도 Java를 주로 사용하고 있습니다. 잘 부탁드려요~

2023-07-31 06:52 UTC, minjae9610 requested changes
자바 천국이 되지 않도록 제가 열심히 노력해야겠군요. ㅠㅠ

2023-07-31 06:52 UTC, minjae9610 commented on README.md
> + |        [![kgh2120](https://avatars.githubusercontent.com/u/76154390)](https://github.com/kgh2120)        |
앞에 스페이스바 하나가 너무 불편한데 정상인가요?
```suggestion
|        [![kgh2120](https://avatars.githubusercontent.com/u/76154390)](https://github.com/kgh2120)        |
```

2023-07-31 06:57 UTC, minjae9610 approved these changes
편-안 하네요

2023-08-01 23:54 UTC, alwzbright97 approved these changes
반갑습니다. 앞으로 잘 부탁드립니다~

2023-08-02 01:45 UTC, merged